### ISSUE TITLE
Merge Assault/Fight

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/PLOVER#1]
As one of the main advocates of keeping these separate, I'd now like to propose after our conversation in Dallas that we consolidate them. I think they're too difficult to distinguish for most coders and that important differences between them can be captured with a mode field.

If I don't hear objections (@jillirvine?), I can make the change and create a pull request.

**Comment by philip-schrodt** [comment]
FWIW, in the current (27-Jan-2017) specification, one- and two-sided violence are easily distinguished by whether or not there is a target (one-sided has a target; in two-sided all of the actors are sources).
