### ISSUE TITLE
More context for people not familiar with CAMEO

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/PLOVER#5]
Early comments back from a classmate who's new to event data made it clear that if we want this accessible to newcomers we need more background/intro that doesn't assume knowledge of CAMEO. I think that should go right up at the beginning of the manual. I'll take a first pass at this.

**Comment by philip-schrodt** [comment]
There's a *lot* of stuff in the CAMEO manual that could be recycled (probably with some updating: most of it was about 15 years old) -- I can send you the LaTeX source if that would be useful.
