### ISSUE TITLE
README states incorrect number of Event Categories

### ISSUE THREAD

**Issue by RyanMullins** [openeventdata/PLOVER#8]
This is super nit picky, but the [PLOVER Event Categories](https://github.com/openeventdata/PLOVER/blob/master/README.md#plover-event-categories-) section states there are "18 event types", however, the list and quad-category breakdown both show 19 categories. 

Does this matter? Probably not. 

Am I a monster who reports this type of inconsistency anyway? Well, we made it this far.

**Comment by ahalterman** [comment]
I knew when I wrote that that I shouldn't be lazy and actually count the categories. It makes me happy to know people are reading this carefully.
